# This file is automatically generated by the Molly Project
# Please see http://docs.mollyproject.org/ for reference documentation

from oauth.oauth import OAuthSignatureMethod_PLAINTEXT
import os.path, imp
from molly.conf.settings import Application, extract_installed_apps, Authentication, ExtraBase, Provider
from molly.utils.media import get_compress_groups

molly_root = imp.find_module('molly')[1]
project_root = os.path.normpath(os.path.dirname(__file__))

ADMINS = (
    ('alex', 'alexliyu2012@gmail.com'),
)

MANAGERS = ADMINS

# DEBUG mode is not recommended in production

DEBUG = True
DEBUG_SECURE = DEBUG
TEMPLATE_DEBUG = DEBUG


# The following settings are sensible defaults. Change if need be. 
LANGUAGE_CODE = 'zh-cn'
TIME_ZONE = 'Europe/London'
USE_I18N = True
SITE_ID = 1

# Site name is used extensively in templates to name the site
SITE_NAME = 'eiimedia'

# Molly can automatically generate the urlpatterns, so it's recommended by
# default to use Molly's urls.py. This doesn't work if you have non-Molly apps
# and may require a custom urls.py to be written
ROOT_URLCONF = 'molly.urls'

# The connection to your database is configured below. We assume you're using
# PostGIS
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'HOST': 'localhost',
        'NAME': 'molly',
        'USER': 'molly',
        'PASSWORD': '6b6RyKNvOnEvbrynYK',
    }
}


# The CACHE_DIR is used by default to store cached map tiles, generated static
# maps, markers, external images, etc
CACHE_DIR = os.path.join(project_root, 'cache')

# API keys are used to access particular services
API_KEYS = {
    'cloudmade': 'None',
    'google_analytics': 'None',
}


# The meat of Molly - application configuration
APPLICATIONS = [

    Application('molly.apps.home', 'home', 'Home',
        display_to_user = True,
    ),
    
    Application('molly.apps.desktop', 'desktop', 'Desktop',
        display_to_user = True,
        twitter_username = 'alexliyu',
        blog_rss_url = 'http://feeds.feedburner.com/mobileoxford',
    ),
    
    Application('molly.apps.podcasts', 'podcasts', 'Podcasts',
        providers = [        ]
        ),
    
    Application('molly.apps.webcams', 'webcams', 'Webcams'),
    
    Application('molly.apps.weather', 'weather', 'Weather',
        location_id = 'bbc/123',
        provider = Provider('molly.apps.weather.providers.BBCWeatherProvider',
            location_id = 123,
        ),
    ),
    
    Application('molly.apps.service_status', 'service_status', 'Service status',
        providers = [        ],
        ),
    
    Application('molly.apps.search', 'search', 'Search',
        providers = [
            Provider('molly.apps.search.providers.ApplicationSearchProvider'), 
        ],
        # Uncomment if you're using a query expansion file
        #query_expansion_file = os.path.join(project_root, 'data', 'query_expansion.txt'),
        display_to_user = False,
    ),
    
    Application('molly.apps.feeds', 'feeds', 'Feeds',
        providers = [
            Provider('molly.apps.feeds.providers.RSSFeedsProvider'),
        ],
        display_to_user = True,
    ),
    
    Application('molly.apps.feeds.news', 'news', 'News'),
    
    Application('molly.apps.feeds.events', 'events', 'Events'),
    
    Application('molly.maps', 'maps', 'Maps',
        display_to_user =True,
    ),
    
    Application('molly.geolocation', 'geolocation', 'Geolocation',
    
        prefer_results_near = (118.115749, 24.471363, 10000),
        providers = [
            Provider('molly.geolocation.providers.PlacesGeolocationProvider'),
        ],
        display_to_user = True,
    ),
    
    Application('molly.apps.feedback', 'feedback', 'Feedback',
        display_to_user = True,
    ),
    
    Application('molly.apps.feature_vote', 'feature_vote', 'Feature suggestions',
        display_to_user = True,
    ),
    
    Application('molly.external_media', 'external_media', 'External Media',
        display_to_user = True,
    ),
    
    Application('molly.wurfl', 'device_detection', 'Device detection',
        display_to_user = True,
        expose_view = True,
    ),
    
    Application('molly.apps.stats', 'stats', 'Statistics',
         display_to_user = True,
     ), 
    
    Application('molly.url_shortener', 'url_shortener', 'URL Shortener',
        display_to_user = True,
    ),
    
    Application('molly.utils', 'utils', 'Molly utility services',
        display_to_user = True,
    ),
    
    Application('molly.auth', 'auth', 'Authentication',
        display_to_user = True,
        secure = True,
        unify_identifiers = ('weblearn:id',),
    ),
    
    Application('molly.apps.places', 'places', 'Places',
        providers = [
            'molly.apps.places.providers.ACISLiveMapsProvider',
            Provider('molly.apps.places.providers.OSMMapsProvider',
                     lat_north=24.671363, lat_south=24.271363,
                     lon_west=117.915749, lon_east=118.315749
            ),
        ],

    ),
    
    Application('molly.apps.transport', 'transport', 'Transport',
            train_station = 'crs:AYW',
        nearby = {
            'bus_stops': ('bus-stop', 5),
        },
        #transit_status_provider = 'molly.apps.transport.providers.TubeStatusProvider',
    
        ),
    
    Application('molly.favourites', 'favourites', 'Favourite pages',
        display_to_user = True,
    ),
    
]


# Middleware classes alter requests and responses before/after they get
# handled by the view. They're useful in providing high-level global
# functionality
MIDDLEWARE_CLASSES = (
    'molly.wurfl.middleware.WurflMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'molly.utils.middleware.ErrorHandlingMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'molly.auth.middleware.SecureSessionMiddleware',
    'molly.apps.stats.middleware.StatisticsMiddleware',
    'molly.url_shortener.middleware.URLShortenerMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
)

# Each entity has a primary identifier which is used to generate the absolute
# URL of the entity page. We can define a list of identifier preferences, so
# that when an entity is imported, these identifier namespaces are looked at in
# order until a value in that namespace is chosen. This is then used as the
# primary identifer.
#IDENTIFIER_SCHEME_PREFERENCE = ('atco', 'osm', 'naptan', 'postcode', 'bbc-tpeg')

# This setting defines which context processors are used - this can affect what
# is available in the context of a view
TEMPLATE_CONTEXT_PROCESSORS = (
    'django.core.context_processors.auth',
    'django.core.context_processors.debug',
    'django.core.context_processors.request',
    'django.core.context_processors.i18n',
    'molly.utils.context_processors.ssl_media',
    'django.contrib.messages.context_processors.messages',
    'molly.wurfl.context_processors.wurfl_device',
    'molly.wurfl.context_processors.device_specific_media',
    'molly.geolocation.context_processors.geolocation',
    'molly.utils.context_processors.full_path',
    'molly.utils.context_processors.site_name',
    #'molly.utils.context_processors.google_analytics',
    'django.core.context_processors.csrf',
)

# This setting defines where Django looks for templates when searching - it
# assumes your overriding templates are defined in '/your/project/templates'
# and you want to have the Molly defaults as a fallback
TEMPLATE_DIRS = (
    os.path.join(project_root, 'templates'),
    os.path.join(molly_root, 'templates'),
)

# This setting changes how Django searches for templates when rendering. The
# default is fine
TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.load_template_source',
    'django.template.loaders.app_directories.load_template_source',
    'django.template.loaders.eggs.load_template_source',
    'molly.utils.template_loaders.MollyDefaultLoader'
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.DefaultStorageFinder',
#    'compressor.finders.CompressorFinder',
)

# Non-Molly apps get added here (plus, tell Django about Molly apps)
INSTALLED_APPS = extract_installed_apps(APPLICATIONS) + (
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.gis',
    'django.contrib.comments',
    'django.contrib.staticfiles',
    'molly.batch_processing',
    'compress',
    'south',
)

# Defines where markers get generated
MARKER_DIR = os.path.join(CACHE_DIR, 'markers')

# This shouldn't need changing
SRID = 27700

# Settings relating to staticfiles
STATIC_ROOT = os.path.join(project_root, 'media') # the location on disk where media is stored
STATIC_URL = '/media/' # The URL used to refer to media
STATICFILES_DIRS = (
    ('', os.path.join(project_root, 'site_media')), # Custom overriding
    ('', os.path.join(molly_root, 'media')), # Molly default media
    ('markers', MARKER_DIR), # Markers
)
ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'

# Settings relating to django-compress
COMPRESS_SOURCE = STATIC_ROOT
COMPRESS_ROOT = STATIC_ROOT
COMPRESS_URL = STATIC_URL
COMPRESS_CSS, COMPRESS_JS = get_compress_groups(STATIC_ROOT)
COMPRESS_CSS_FILTERS = ('molly.utils.compress.MollyCSSFilter',) # CSS filter is custom-written since the provided one mangles it too much
COMPRESS_CSSTIDY_SETTINGS = {
    'remove_bslash': True, # default True
    'compress_colors': True, # default True
    'compress_font-weight': True, # default True
    'lowercase_s': False, # default False
    'optimise_shorthands': 0, # default 2, tries to merge bg rules together and makes a hash of things
    'remove_last_': False, # default False
    'case_properties': 1, # default 1
    'sort_properties': False, # default False
    'sort_selectors': False, # default False
    'merge_selectors': 0, # default 2, messes things up
    'discard_invalid_properties': False, # default False
    'css_level': 'CSS2.1', # default 'CSS2.1'
    'preserve_css': False, # default False
    'timestamp': False, # default False
    'template': 'high_compression', # default 'highest_compression'
}
COMPRESS_JS_FILTERS = ('compress.filters.jsmin.JSMinFilter',)
COMPRESS = not DEBUG     # Only enable on production (to help debugging)
COMPRESS_VERSION = True  # Add a version number to compressed files.
